# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'azdevopssc'
    subscriptionId: 'ad62f123-368f-43bc-ad2c-d9aa00a5198d'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Demo-IaC-KIBB'
    location: 'Southeast Asia'
    templateLocation: 'Linked artifact'
    csmFile: 'azuredeploy.json'
    csmParametersFile: 'azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'Test VM'